//
//  MessagesViewController.swift
//  iMessageApp
//
//  Created by Chad Etzel on 9/27/21.
//

import UIKit
import Messages
import CoreData

class MessagesViewController: MSMessagesAppViewController {

    let extensionCoreDataUpdateListener = CoreDataDistributedUpdateListener()

    @IBAction func _didTapAddAThingButton(_ sender: Any) {
        let color = UIColor(hue: CGFloat.random(in: 0.0 ... 1.0), saturation: 1.0, brightness: 1.0, alpha: 1.0)
        let amount = Int64.random(in: 0 ... 1000)

        let thingPrimitive = ThingPrimitive(amount: amount, color: color, thing: nil)

        let _ = Thing.upsertThingFromPrimitive(thingPrimitive)
    }



    // MARK: - Conversation Handling

    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.

        // Use this method to configure the extension and restore previously stored state.
    }

    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dismisses the extension, changes to a different
        // conversation or quits Messages.

        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }

    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.

        // Use this method to trigger UI updates in response to the message.
    }

    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }

    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.

        // Use this to clean up state related to the deleted message.
    }

    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.

        // Use this method to prepare for the change in presentation style.
    }

    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.

        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

}
